/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_janweehsia_Greeting */

#ifndef _Included_top_janweehsia_Greeting
#define _Included_top_janweehsia_Greeting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_janweehsia_Greeting
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_janweehsia_Greeting_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
